# -*- coding: utf-8 -*-
"""internshipday 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRzII4KWFNQYRmmb4LYhNFgoE9_1a-rh
"""

import pandas as pd

df=pd.read_csv("/content/Zudio_sales_data.csv")

df

df.head()

df.tail()

df.tail(10)

df.info()

df.shape

df.dtypes

df.describe()

df['Store Number']

df[['Store Number','Postal Code']]

ef=pd.read_csv("/content/titanic uncleaned.csv")

ef

ef.head()

ef.tail()

ef.tail()

ef.tail(10)

ef.info()

ef.shape

ef.dtypes

ef.describe()

ef['PassengerId']

ef[['PassengerId','Survived']]

ef.isnull()

ef.isnull().sum()

ef['Age_mean_imputed']=ef['Age'].fillna(ef['Age'].mean())
ef['Age_median_imputed']=ef['Age'].fillna(ef['Age'].median())

ef['Cabin_mode_imputed']=ef['Cabin'].fillna(ef['Cabin'].mode()[0])

ef[['Age','Age_mean_imputed','Age_median_imputed']]

import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=ef,x='Embarked',y='Fare',palette='pastel')

plt.title('Boxplot of Age by PassengerClass',fontsize=16)
plt.xlabel('PassengerClass',fontsize=12)
plt.ylabel('Age',fontsize=12)
plt.show()

from sklearn.preprocessing import LabelEncoder

encoded_data=ef.copy()

label_encoder=LabelEncoder()
encoded_data['Sex_Label']=label_encoder.fit_transform(encoded_data['Sex'])

one_hot_encoded=pd.get_dummies(encoded_data['Embarked'],prefix='Embarked')
encoded_data=pd.concat([encoded_data,one_hot_encoded],axis=1)
pclass_mapping={1:'First',2:'Second',3:'Third'}

encoded_data['Pclass_Category'] = encoded_data['Pclass'].map(pclass_mapping)
print(encoded_data[['Sex', 'Sex_Label', 'Embarked', 'Embarked_Q', 'Embarked_S', 'Embarked_C', 'Pclass', 'Pclass_Category']].head())

from sklearn.preprocessing import MinMaxScaler,StandardScaler

File_path='/content/titanic uncleaned.csv'
titanic_data=pd.read_csv(File_path)

numerical_columns=['Age','Fare','Pclass']

titanic_data.dropna(subset=numerical_columns,inplace=True)

minmax_scaler=MinMaxScaler()
standard_scaler=StandardScaler()

titanic_data['Age_MinMax']=minmax_scaler.fit_transform(titanic_data[['Age']])
titanic_data['Fare_MinMax']=minmax_scaler.fit_transform(titanic_data[['Fare']])
titanic_data['Age_Standard']=standard_scaler.fit_transform(titanic_data[['Age']])
titanic_data['Fare_Standard']=standard_scaler.fit_transform(titanic_data[['Fare']])

titanic_data[['Age','Age_MinMax','Age_Standard']].head()